### ISSUE TITLE
Data objects with suffix Request generate invalid output.

### ISSUE THREAD

**Issue by ChristianAlexander** [FacilityApi/FacilityCSharp#2]
Given the following example, two files called `CreateWidgetRequestDto.g.cs` are created. I observed this using the web editor. Fsdgencsharp just creates one of the files, and the resulting code does not function.

There should be an error when a data object has the suffix `Request` (or `Response`).

```
/// Example service for widgets.
[http(url: "http://local.example.com/v1")]
[csharp(namespace: Facility.ExampleApi)]
service ExampleApi
{
	/// Creates a new widget.
	[http(method: POST, path: "/widgets/", code: 201)]
	method createWidget
	{
		/// The widget to create.
		[http(from: body)]
		widget: CreateWidgetRequest;
	}:
	{
		/// The created widget.
		[http(from: body)]
		widget: Widget;
	}

	/// A widget creation request.
	data CreateWidgetRequest
	{
		/// The weight of the widget.
		name: string;
	}

	/// A widget.
	data Widget
	{
		/// A unique identifier for the widget.
		id: string;

		/// The name of the widget.
		name: string;

		/// The weight of the widget.
		[obsolete]
		weight: double;
	}
}

```

**Comment by ejball** [comment]
Agreed; thanks for the bug report.

**Comment by ejball** [comment]
Possible solutions:

* Report an error when there's a naming conflict.
* Put method-generated DTOs in a separate namespace from data-generated DTOs.
* Drop the `Dto` suffix from method-generated DTOs, e.g. `CreateWidgetRequest` for the method and `CreateWidgetRequestDto` for the data.

cc @ddunkin

**Comment by ddunkin** [comment]
Dropping the suffix seems pretty reasonable to me.

**Comment by ejball** [comment]
I agree, it is tempting. It doesn't help them if they create an `enum CreateWidgetRequest` but that's considerably less likely, I hope. (I should still improve the error message for it.)

**Comment by ejball** [comment]
I really want to avoid breaking changes that require major code changes for existing users.

In addition to failing on naming conflict, we could add `[csharp]` options to customize code generation. Various ideas:

```
[csharp(dtoNamespace: Dtos)] // option 2
[csharp(methodDtoSuffix: "")] // option 3
[csharp(methodDtoSuffix: MethodDto, dataDtoSuffix: DataDto)] // another option
[csharp(requestDtoSuffix: RequestData, responseDtoSuffix: ResponseData)] // another option
service XyzzyApi
{
    [csharp(name: CreateWidgetMethod)] // per-method override for interface method, etc.
    [csharp(dtoName: CreateWidgetMethod)] // per-method override for just the DTOs
    [csharp(requestDtoName: CreateWidgetRequest, responseDtoName: CreateWidgetResponse)] // per-method override for just the DTOs
    method createWidget { ... }: { ... }

    [csharp(name: CreateWidgetRequestFieldDto)] // per-DTO override
    data createWidgetRequest { ... }
}
```
