### ISSUE TITLE
Provide public const string values for enums.

### ISSUE THREAD

**Issue by StephenCleary** [FacilityApi/FacilityCSharp#30]
Public const string values for enums would enable the use of switch expressions when mapping or doing other handling.

Current mapping code is one of:

```C#
if (source == ApiTaskStatus.Unclaimed)
	return TaskStatus.Unclaimed;
if (source == ApiTaskStatus.Pending)
	return TaskStatus.Pending;
if (source == ApiTaskStatus.Completed)
	return TaskStatus.Completed;
if (source == ApiTaskStatus.Rejected)
	return TaskStatus.Rejected;

throw new InvalidOperationException($"Unhandled task status: {source}");
```

or:

```C#
source switch
{
	_ when source == ApiTaskStatus.Unclaimed => TaskStatus.Unclaimed,
	_ when source == ApiTaskStatus.Pending => TaskStatus.Pending,
	_ when source == ApiTaskStatus.Completed => TaskStatus.Completed,
	_ when source == ApiTaskStatus.Rejected => TaskStatus.Rejected,
	_ => throw new InvalidOperationException($"Unhandled task status: {source}"),
}
```

Desired mapping code:

```C#
source switch
{
	ApiTaskStatus.Unclaimed => TaskStatus.Unclaimed,
	ApiTaskStatus.Pending => TaskStatus.Pending,
	ApiTaskStatus.Completed => TaskStatus.Completed,
	ApiTaskStatus.Rejected => TaskStatus.Rejected,
	_ => throw new InvalidOperationException($"Unhandled task status: {source}"),
}
```

**Comment by ejball** [comment]
Thanks, @bgrainger!

**Comment by ejball** [comment]
If we want to maintain backward-compatibility, we need to decide where to store the constant strings. `ApiTaskStatus.Pending` is already being used, so we could store them in a static nested class, e.g. `ApiTaskStatus.Strings.Pending`, or in a separate static top-level class, e.g. `ApiTaskStatusStrings.Pending`. Then we could do something like:

```csharp
source.ToString() switch
{
	ApiTaskStatusStrings.Unclaimed => TaskStatus.Unclaimed,
	ApiTaskStatusStrings.Pending => TaskStatus.Pending,
	ApiTaskStatusStrings.Completed => TaskStatus.Completed,
	ApiTaskStatusStrings.Rejected => TaskStatus.Rejected,
	_ => throw new InvalidOperationException($"Unhandled task status: {source}"),
}
```

If we want to maintain case-insensitivity, we'd also need to ensure that the string returned from `ToString()` is case normalized.

**Comment by ejball** [comment]
If we are open to backward-incompatibility, there are other possibilities.

We could just use a `string` for enum fields and a static class of string constants. This would lose type safety and case-insensitivity. I'd be more concerned about the former.

We could use a wrapper around a standard numeric enum. This would be nice because we could leverage refactoring features like "generate switch cases for all values". However, maintaining binary compatibility with changing numeric enums would be difficult as the API evolves.

**Comment by StephenCleary** [comment]
Using different names for the const strings or moving them to another type is fine with me. I like the type-safe enums and I agree an `enum` wrapper could bring upgrade problems.
