### ISSUE TITLE
Support async serialization/deserialization in JsonHttpContentSerializer

### ISSUE THREAD

**Issue by ddunkin** [FacilityApi/FacilityCSharp#51]
Newtonsoft.Json doesn't support async serialization, but System.Text.Json does.

**Comment by ejball** [comment]
`2.14.0-beta.2` serializes/deserializes to a memory stream and then uses async I/O from that to get around this issue.

We could do async serialization from `System.Text.Json` but it would be good to confirm that there are tangible performance gains before committing to it.

**Comment by ejball** [comment]
Using a memory stream efficiently was getting too complicated. I think #60 resolves this issue. The Newtonsoft.Json serializer just doesn't use async. In the unlikely event that an ASP.NET Core project wants to use Json.NET, they can work around the lack of async easily enough with `AllowSynchronousIO`.

**Comment by ejball** [comment]
"Fixed" by using `SystemTextJsonServiceSerializer`, the new default for generated code as of [2.14.0](https://github.com/FacilityApi/FacilityCSharp/blob/master/ReleaseNotes.md#2140). Please reopen if you think it is important that we support async with Newtonsoft.Json.
