### ISSUE TITLE
Support JsonSerializerContext source generation for System.Text.Json

### ISSUE THREAD

**Issue by ddunkin** [FacilityApi/FacilityCSharp#52]
https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/

**Comment by ejball** [comment]
Perhaps `SystemTextJsonServiceSerializer` could keep a thread-safe dictionary of `Type` to `JsonTypeInfo` and the generated `HttpMapping` could have a static constructor that registered each of the request and response DTOs.

**Comment by ejball** [comment]
See comment: https://github.com/FacilityApi/FacilityCSharp/pull/71#issuecomment-2166946348
