### ISSUE TITLE
Support asynchronous I/O

### ISSUE THREAD

**Issue by jzbrooks** [FacilityApi/FacilityCSharp#56]
Synchronous I/O has been disabled by default since netcore 3.0. Apparently it has been a source of thread starvation. https://github.com/dotnet/docs/issues/14835

Ultimately, I'd like to remove the following code from my project:
```csharp
    services.Configure<KestrelServerOptions>(options =>
    {
        options.AllowSynchronousIO = true;
    });

    services.Configure<IISServerOptions>(options =>
    {
        options.AllowSynchronousIO = true;
    });
```

**Comment by ejball** [comment]
`2.14.0-beta.2` should fix this.

**Comment by jzbrooks** [comment]
It turned out `JsonHttpContentSerializerSettings.ForceAsyncIO` wasn't properly set for my project. Closing this.
