### ISSUE TITLE
Improve Unit Testing Breadth

### ISSUE THREAD

**Issue by ELanning** [FacilityApi/FacilityCSharp#66]
A common recurring issue I've run into when writing unit tests for generated services

1. Setup some basic unit test,
```
public async Task GetUserSucceeds()
{
    var service = await Service.GetUser();
    // ... verify the result is as expected ...
}
```
2. The test passes.
3. The functionality fails when used in a web server context, because property checking is done there. Eg `[Required]` and other properties consumers can add.

Writing `n` integration tests does not scale well, as integration tests are generally slow and costly. It would be nice to be able to have these checks done in unit tests, if wanted.

Unrelated aside: FacilityApi is an impressive piece of engineering, and has greatly improved velocity for many projects I've worked on.

**Comment by ejball** [comment]
`ServiceDelegators.Validate` may be what you are looking for. [This unit test](https://github.com/FacilityApi/FacilityCSharp/blob/9edaa23b393be9a457563590afe70ecb7539374e/tests/Facility.ConformanceApi.UnitTests/DelegationTests.cs#L73) shows how it can be used to wrap your API interface implementation in a delegating implementation that validates requests and responses.

**Comment by ELanning** [comment]
Thanks, that looks exactly like what I need 👍
