### ISSUE TITLE
Adapt ASP.NET Core HTTP request/response types to the types that Facility natively supports.

### ISSUE THREAD

**Issue by chrisculy** [FacilityApi/FacilityCSharp#9]
See internal FacilityActionFilter class (based on Microsoft.AspNetCore.Mvc.WebApiCompatShim) for details.

**Comment by ejball** [comment]
Published: https://www.nuget.org/packages/Facility.AspNetCore/2.0.1-alpha1

The [`FacilityActionFilter`](https://github.com/FacilityApi/FacilityAspNet/blob/master/src/Facility.AspNetCore/FacilityActionFilter.cs) in `Facility.AspNetCore` doesn't do any logging. Hopefully logging code can be an orthogonal concern, e.g. moved to a separate action filter.
